# Generated by Django 5.2.11 on 2026-03-01 12:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('unite', models.CharField(choices=[('KG', 'kg'), ('UNITE', 'unite'), ('LITRE', 'litre')], default='UNITE', max_length=10)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='EspaceVert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('type_espace', models.CharField(choices=[('PARC', 'Parc'), ('JARDIN', 'Jardin public'), ('SQUARE', 'Square'), ('STADE', 'Stade')], max_length=20)),
                ('superficie_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('zone', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Espace vert',
                'verbose_name_plural': 'Espaces verts',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ActiviteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('objet_type', models.CharField(max_length=120)),
                ('objet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('zone_assignee', models.CharField(blank=True, max_length=120)),
                ('agents', models.ManyToManyField(blank=True, related_name='equipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('etat', models.CharField(choices=[('BON', 'Bon'), ('USE', 'Use'), ('CASSE', 'Casse')], default='BON', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='gestion.espacevert')),
            ],
            options={
                'ordering': ['espace__nom', 'nom'],
                'unique_together': {('espace', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_intervention', models.CharField(choices=[('TONTE', 'Tonte de pelouse'), ('ARROSAGE', 'Arrosage'), ('FEUILLES', 'Ramassage des feuilles'), ('REPARATION', 'Reparation'), ('AUTRE', 'Autre')], max_length=30)),
                ('planifiee_le', models.DateTimeField()),
                ('terminee_le', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PREVUE', 'Prevue'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminee'), ('ANNULEE', 'Annulee')], default='PREVUE', max_length=20)),
                ('cout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_creees', to=settings.AUTH_USER_MODEL)),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='gestion.equipe')),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='gestion.espacevert')),
            ],
            options={
                'ordering': ['-planifiee_le'],
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('categorie', models.CharField(choices=[('TONDEUSE', 'Tondeuse'), ('TAILLE_HAIE', 'Taille-haie'), ('AUTRE', 'Autre')], max_length=30)),
                ('etat', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_PANNE', 'En panne'), ('EN_REPARATION', 'En reparation'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', max_length=30)),
                ('quantite_totale', models.PositiveIntegerField(default=1)),
                ('quantite_disponible', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('nom', 'categorie')},
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entree'), ('SORTIE', 'Sortie')], max_length=10)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='gestion.articlestock')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('INTERVENTION', 'Intervention'), ('SIGNALEMENT', 'Signalement'), ('STOCK', 'Stock'), ('SYSTEME', 'Systeme')], max_length=20)),
                ('titre', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('url_cible', models.CharField(blank=True, max_length=255)),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='MOYENNE', max_length=20)),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours'), ('RESOLU', 'Resolu'), ('REJETE', 'Rejete')], default='OUVERT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='gestion.equipe')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_crees', to=settings.AUTH_USER_MODEL)),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='gestion.equipement')),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='gestion.espacevert')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
