# Generated by Django 5.2.11 on 2026-03-01 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('fonction', models.CharField(blank=True, max_length=120)),
                ('zone_reference', models.CharField(blank=True, max_length=120)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('role_principal', models.CharField(blank=True, choices=[('GestionnaireParticulier', 'GestionnaireParticulier'), ('GestionnaireGlobal', 'GestionnaireGlobal'), ('Maire', 'Maire')], max_length=40)),
                ('actif_terrain', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
